version: 2

linters:
  default: all
  disable:
    - depguard  # not currently used
    - noinlineerr  # not currently used
    - wsl  # replaced by 'wsl_v5'
  settings:
    misspell:
      locale: US
    recvcheck:
      exclusions:
        - '*.UnmarshalText'

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      reformat-tags: false
