version: 2

project_name: kadumper

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd
    ldflags:
      - -s -w
      - -X main.BuildDate={{.Date}}
      - -X main.GitBranch={{.Branch}}
      - -X main.GitCommit={{.ShortCommit}}
      - -X main.Version={{.Version}}
    no_unique_dist_dir: '{{.IsSingleTarget}}'

archives:
  - format_overrides:
      - goos: windows
        formats: ["zip"]
